// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzW6i7RLBWJRC8DDn2S5S87hLubnaYbc',
    appId: '1:1073356550593:web:3cfceabcc0b4c4316c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    authDomain: 'summerproject-987e0.firebaseapp.com',
    storageBucket: 'summerproject-987e0.appspot.com',
    measurementId: 'G-GM4D0Z1L26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_A1vVHJVdgN6LUjN4pcbqq6lSfyxRSQs',
    appId: '1:1073356550593:android:a1f0895352c0a0ef6c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    storageBucket: 'summerproject-987e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDscG4Jzf5nuYcHny-Cr2ee8IkrCYWgw_g',
    appId: '1:1073356550593:ios:f57f93ddcba1635c6c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    storageBucket: 'summerproject-987e0.appspot.com',
    androidClientId: '1073356550593-jr4g46thk7l9shmd64ptr3g3255hc1tg.apps.googleusercontent.com',
    iosClientId: '1073356550593-g90psl78umkpsavqrj4tb2ttcf3p9ckj.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDscG4Jzf5nuYcHny-Cr2ee8IkrCYWgw_g',
    appId: '1:1073356550593:ios:f57f93ddcba1635c6c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    storageBucket: 'summerproject-987e0.appspot.com',
    androidClientId: '1073356550593-jr4g46thk7l9shmd64ptr3g3255hc1tg.apps.googleusercontent.com',
    iosClientId: '1073356550593-g90psl78umkpsavqrj4tb2ttcf3p9ckj.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMzW6i7RLBWJRC8DDn2S5S87hLubnaYbc',
    appId: '1:1073356550593:web:daa1c5dfa4bcd8f66c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    authDomain: 'summerproject-987e0.firebaseapp.com',
    storageBucket: 'summerproject-987e0.appspot.com',
    measurementId: 'G-Y7GM6XQ0SF',
  );
}
